//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionDocsSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantEducation
    {
        public int ApplicantEducationID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> EducationalLevelID { get; set; }
    
        public virtual Applicants Applicants { get; set; }
        public virtual EducationalLevels EducationalLevels { get; set; }
    }
}
