//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionDocsSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ApplicationID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> ProgramTypeID { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Applicants Applicants { get; set; }
        public virtual ProgramTypes ProgramTypes { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
    }
}
