//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionDocsSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicants()
        {
            this.ApplicantEducation = new HashSet<ApplicantEducation>();
            this.Applications = new HashSet<Applications>();
            this.Documents = new HashSet<Documents>();
        }
    
        public int ApplicantID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> ApplicationStatusID { get; set; }
        public Nullable<bool> ConfirmedByAdmin { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string RegistrationAddress { get; set; }
        public string ResidentialAddress { get; set; }
        public Nullable<bool> DataConsentGiven { get; set; }
        public Nullable<int> EducationalLevelID { get; set; }
        public Nullable<int> ProgramTypeID { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantEducation> ApplicantEducation { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual EducationalLevels EducationalLevels { get; set; }
        public virtual ProgramTypes ProgramTypes { get; set; }

    }
}
